version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env
  app:
    build: imgcollector
    container_name: django-gunicorn
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
      - DJANGO_KEY=example_key_for_django_3929838
      - HOST=localhost
      - NGINX_DOCKER=1
    volumes:
      - /static:/static
    depends_on:
      - db
    command:
      "gunicorn --workers=3 --threads=3 --bind=0.0.0.0:8000 imgcollector.wsgi:application"

  nginx:
    image: nginx:1.18
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - app