# Generated by Django 4.0.6 on 2022-07-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_module', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
