# Generated by Django 4.0.6 on 2022-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_module', '0002_alter_customuser_managers_remove_customuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
