# Generated by Django 4.0.6 on 2022-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_module', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
