# Generated by Django 4.0.6 on 2022-07-07 19:47

from django.db import migrations, models
import rest_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_module', '0004_remove_customuser_is_admin_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image200',
            field=models.ImageField(null=True, upload_to=rest_module.models.get_file_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='image400',
            field=models.ImageField(null=True, upload_to=rest_module.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=rest_module.models.get_file_path),
        ),
    ]
