# Generated by Django 4.0.6 on 2022-07-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_module', '0005_photo_image200_photo_image400_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image200',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image400',
        ),
    ]
