# Generated by Django 4.0.6 on 2022-07-08 15:31

from django.db import migrations, models
import rest_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_module', '0006_remove_photo_image200_remove_photo_image400'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail_200',
            field=models.ImageField(editable=False, null=True, upload_to=rest_module.models.get_file_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_400',
            field=models.ImageField(editable=False, null=True, upload_to=rest_module.models.get_file_path),
        ),
    ]
